DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS artpiece;
DROP TABLE IF EXISTS wallet;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE wallet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  balance INTEGER NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  artpiece_id INTEGER,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (artpiece_id) REFERENCES artpiece (id)
);

CREATE TABLE artpiece (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  uploadtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  artpiecename TEXT NOT NULL,
  image BLOB NOT NULL,
  imagetype TEXT NOT NULL,
  value DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);
